import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Grid } from './components/Grid'
import Link from 'next/link'
import { ChartIcon, CreditIcon, ServerIcon, UserIcon } from './components/Icons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const sidemenus = [
    { href: "/account", icon: <UserIcon />, text: "Account" },
    { href: "/analytics", icon: <ChartIcon />, text: "Analytics" },
    { href: "/payment", icon: <CreditIcon />, text: "Payment" },
    {
      href: "/settings", icon: <ServerIcon />, text: "Settings"
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid>
          <div className="md:sticky md:top-0 col-span-12 md:col-span-2 grid grid-cols-12 md:grid-cols-1 border-b md:border-b-0 border-neutral-content w-full h-fit md:w-fit mx-auto">
            {sidemenus.map(menu => {
              return (
                <Link href={menu.href} className="flex mb-2 last:mb-0 col-span-3 md:col-span-1" key={menu.text}>
                  {menu.icon}
                  <p className="ml-2">{menu.text}</p>
                </Link>
              )
            })}
          </div>
          <div className="col-span-12 md:col-span-10 md:border-l border-neutral-content">
            {children}
          </div>
        </Grid>
      </body>
    </html>
  )
}
